# helper.sh
# Florencia D'Andrea, 2022

# Helper script to remove pipeline intermediate files.
# Script created for the live demo 
# to use before explaining  the command `make clean`.

# Usage: bash helper.sh


# Remove all the files generated by the pipeline.
rm -f **/*.dat
rm -f **/*.png
rm -f **/*.html